all:
	latexmk -pdf sample-acmlarge.tex
	mv sample-acmlarge.pdf final-report.pdf
	make clean
clean:
	rm -f *.fdb_latexmk *.fls *.dvi *.aux *.log *.toc *.glo *.idx *.ilg *.out *.bbl *.thm *.blg *.lot *.lof